platform :ios, '9.0'

target 'yunze_hw9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yunze_hw9

    pod "McPicker"
    pod "Alamofire"
    pod "SwiftyJSON"
    pod "SwiftSpinner"
    pod "EasyToast"
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod "SearchTextField"
end
